name: Terraform-Backend

on:
  push:
    branches: ["main"]

  workflow_dispatch:  
jobs:
 build:
  runs-on: self-hosted

  steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Azure Login
    uses: azure/login@v2
    with:
       client-id: 81d20314-ef05-46eb-8bdf-473e9e20664f
       tenant-id: 2a12578d-9130-4f98-9fe6-c8a422505a24
       subscription-id: 2b0a7e07-53fd-47f9-85cf-6fbc0364e35f
       client-secret: vXo8Q~rv~pWtle3x1wU3JgM.lB7CLvWIQOU3GbCC

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Init
    run: terraform init

  - name: Terraform Validate
    run: terraform validate

  - name: Terraform Plan
    run: terraform plan

  - name: Terraform Apply
    run: terraform apply -auto-approve
