
name: Terraform-Backend
on:

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: az Login
        uses: az login --service-principal --username 81d20314-ef05-46eb-8bdf-473e9e20664f --password vXo8Q~rv~pWtle3x1wU3JgM.lB7CLvWIQOU3GbCC --tenant 2a12578d-9130-4f98-9fe6-c8a422505a24
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve


